### ISSUE TITLE
pull access denied for andrerc1/ansible, repository does not exist or may require 'docker login': denied: ...

### ISSUE THREAD

**Issue by zieglerjm** [AndreCox/PIBaker#6]
Is there another public docker image that can be used?

**Comment by zieglerjm** [comment]
I tried to replace it with alpinelinux/ansible but am getting:

 - Container pibaker-ansible-playbook-1  Starting                                                                                                               1.0s 
Error response from daemon: failed to create task for container: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: exec: "-i": executable file not found in $PATH: unknown

**Comment by AndreCox** [comment]
This sounds like you don't have docker set up properly as it should build the container anderc1/ansible from the source code

**Comment by AndreCox** [comment]
os.system('docker build -t andrerc1/ansible ./ansible') 

This command builds the image

**Comment by zieglerjm** [comment]
I tried on another PC with Windows 10 vs 11.  How do we fix the cert problem?

+ pip install python-keyczar docker-py boto3 botocore
Collecting python-keyczar
Could not fetch URL https://pypi.python.org/simple/python-keyczar/: There was a problem confirming the ssl certificate: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:726) - skipping
Could not find a version that satisfies the requirement python-keyczar (from versions: )
No matching distribution found for python-keyczar

**Comment by AndreCox** [comment]
You should not need to do any of that the setup file literally has 0 dependencies except for os which is included with python

**Comment by AndreCox** [comment]
I'm closing this issue as this appears to be an issue related to setup/dependencies I will consider reopening if more details can be provided.
