### ISSUE TITLE
docker-compose required, but not installed

### ISSUE THREAD

**Issue by SmallCoder13** [AndreCox/PIBaker#9]
Hi,

So I've noticed lately, that on the last two machines I've tried to install this on, both times I've had to install docker-compose manually (meaning, it wasn't installed when I installed docker). I just wanted to point out that adding docker-compose to your requirements might be good cause I've can't tell you how many packages I've tried to install, but gave up just because I couldn't figure out how to install a dependency that was listed in the requirements. Just a thought :-)

**Comment by AndreCox** [comment]
Please would you let me know what os you are using?

**Comment by SmallCoder13** [comment]
ubuntu 23.04 or 24.04 LTS

**Comment by AndreCox** [comment]
Ah yes for those OS's docker and docker-compose are 2 separate packages I will add a requirement for that

**Comment by AndreCox** [comment]
I have added a note to the read me, I hope that is a good enough fix for this problem
